FROM python:3.9

COPY . /source

RUN pip install git+https://github.com/oda-hub/nb2workflow@galaxy-tool-test-remotefile#egg=nb2workflow[galaxy]
RUN pip install /source[galaxy] && rm -r /source

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

CMD ["odabot", "--settings", "/settings.toml", "make-galaxy-tools", "--loop", "10"]